package Entity;

/**
 *
 * @author Ho Wei Lee
 */
public class Item{
    private String itemId;
    private String itemPic;
    private String itemName;
    private String itemDesc;
    private double cost;
    private double bidPrice;
    private String endBidTime;
    private String ownerID;

    public Item(String itemId, String itemPic, String itemName, String itemDesc, double cost, double bidPrice, String ownerID) {
        this.itemId = itemId;
        this.itemPic = itemPic;
        this.itemName = itemName;
        this.itemDesc = itemDesc;
        this.cost = cost;
        this.bidPrice = bidPrice;
        this.ownerID = ownerID;
        endBidTime="Not yet bidding";
    }

    public Item(String itemId, String itemPic, String itemName, String itemDesc, double cost, double bidPrice,String endBidTime, String ownerID) {
        this.itemId = itemId;
        this.itemPic = itemPic;
        this.itemName = itemName;
        this.itemDesc = itemDesc;
        this.cost = cost;
        this.bidPrice = bidPrice;
        this.ownerID = ownerID;
        this.endBidTime=endBidTime;
    }
    
    public String getItemId() {
        return itemId;
    }

    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    public String getItemPic() {
        return itemPic;
    }

    public void setItemPic(String itemPic) {
        this.itemPic = itemPic;
    }

    public String getItemName() {
        return itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getItemDesc() {
        return itemDesc;
    }

    public void setItemDesc(String itemDesc) {
        this.itemDesc = itemDesc;
    }

    public double getCost() {
        return cost;
    }

    public void setCost(double cost) {
        this.cost = cost;
    }

    public double getBidPrice() {
        return bidPrice;
    }

    public void setBidPrice(double bidPrice) {
        this.bidPrice = bidPrice;
    }

    public String getOwnerID() {
        return ownerID;
    }

    public void setOwnerID(String ownerID) {
        this.ownerID = ownerID;
    }

    public String getEndBidTime() {
        return endBidTime;
    }

    public void setEndBidTime(String endBidTime) {
        this.endBidTime = endBidTime;
    }
    
    public static String getNextID(String lastID){
        return autoGeneratedID(lastID);
    }
    
    @Override
    public String toString() {
        return itemId + "#" + itemPic + "#" + itemName + "#" + itemDesc + "#" + cost+"#"+ bidPrice + "#" + endBidTime +"#" + ownerID;
    }
    
    private static String autoGeneratedID(String lastID){
        char ch=lastID.charAt(0);
        int idCount=Integer.parseInt(lastID.substring(1))+1;
        if(idCount<10){
            return ch+String.format("000%d", idCount);
        }else if(idCount>=10&&idCount<100){
            return ch+String.format("00%d", idCount);
        }else if(idCount>=100&&idCount<1000){
            return ch+String.format("0%d", idCount);
        }else{
            return ch+String.format("%d", idCount);
        }
    }
}